# Cloud Build configuration for CODEC AI Caller
# This builds and deploys both backend and frontend to Cloud Run

substitutions:
  _REGION: australia-southeast1
  _BACKEND_SERVICE: codec-backend
  _FRONTEND_SERVICE: codec-frontend

steps:
  # Build Backend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-backend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
      - './backend'

  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest'
      - '--build-arg'
      - 'NEXT_PUBLIC_API_URL=https://${_BACKEND_SERVICE}-${PROJECT_NUMBER}.${_REGION}.run.app'
      - './frontend'

  # Push Backend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-backend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
    waitFor: ['build-backend']

  # Push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA'
    waitFor: ['build-frontend']

  # Deploy Backend to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-backend'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - '${_BACKEND_SERVICE}'
      - '--image'
      - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '8080'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'
      - '--set-secrets'
      - 'TWILIO_ACCOUNT_SID=twilio-account-sid:latest,TWILIO_AUTH_TOKEN=twilio-auth-token:latest,TWILIO_PHONE_NUMBER=twilio-phone-number:latest,GEMINI_API_KEY=gemini-api-key:latest,ELEVENLABS_API_KEY=elevenlabs-api-key:latest,ELEVENLABS_VOICE_ID=elevenlabs-voice-id:latest,GOOGLE_SEARCH_API_KEY=google-search-api-key:latest,GOOGLE_SEARCH_ENGINE_ID=google-search-engine-id:latest'
    waitFor: ['push-backend']

  # Get Backend URL and Deploy Frontend
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_BACKEND_SERVICE} --region=${_REGION} --format='value(status.url)')
        echo "Backend URL: $BACKEND_URL"

        gcloud run deploy ${_FRONTEND_SERVICE} \
          --image gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA \
          --region ${_REGION} \
          --platform managed \
          --allow-unauthenticated \
          --port 3000 \
          --memory 256Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 5 \
          --set-env-vars "NEXT_PUBLIC_API_URL=$BACKEND_URL"
    waitFor: ['deploy-backend', 'push-frontend']

  # Update Backend with its own URL for SERVER_DOMAIN
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'update-backend-domain'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        BACKEND_URL=$(gcloud run services describe ${_BACKEND_SERVICE} --region=${_REGION} --format='value(status.url)')
        SERVER_DOMAIN=$(echo $BACKEND_URL | sed 's|https://||')
        echo "Setting SERVER_DOMAIN to: $SERVER_DOMAIN"

        gcloud run services update ${_BACKEND_SERVICE} \
          --region ${_REGION} \
          --set-env-vars "SERVER_DOMAIN=$SERVER_DOMAIN"
    waitFor: ['deploy-backend']

images:
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_BACKEND_SERVICE}:latest'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/${_FRONTEND_SERVICE}:latest'

options:
  logging: CLOUD_LOGGING_ONLY
